#include "with_mesh_povray/camera.inc"
#include "with_mesh_povray/frame0003.inc"
#include "with_mesh_povray/surface.inc"
#include "with_mesh_povray/surface.inc"
#include "with_mesh_povray/surface.inc"
#include "with_mesh_povray/surface.inc"
#include "with_mesh_povray/surface.inc"
